### ISSUE TITLE
Bypass

### ISSUE THREAD

**Issue by FakeRoba** [Triscuit2311/GoblinAC#3]
I was wondering that if i had executor and i did execute this code:

```
function Cheater(...)
    TriggerEvent('Goblin::Client::EventProxy', ...)
end

Cheater("FakeScript::Server::GiveMoney", 99999999, 9999999, "Cash")
```

wouldnt that bypass system?

**Comment by Triscuit2311** [comment]
If you had a server script that would accept these arguments from a proxy call, then yes it would.

However, It's worth noting that employed properly, the original events should be hidden from the client to begin with. But like I mentioned in the readme, in the "Couldn't this be bypassed?" section, this feature on it's own is not a complete defense.

There are a few things you can do if you want to prevent this attack from being viable:

First, think ahead when designing your events system, and don't trust the client as best you can. 

Second, require authentication, and check parameters.

Third, business on the backend; use the server to track and check states, not the client.

If you're already working in a FiveM environment, these might not all be viable, and I know sometimes you need to work with what you have. In this case, if you wanted to use GoblinAC really protect from people injecting lua, you can either hot load your lua scripts via piping which can be done in C#, or you can use LuaC to precompile scripts, or you can create a new runtime environment for your lua scripts.

Additionally, you can provide some integrity checks to the FiveM client environment, but that's far outside the scope of this project. Honestly, most of this response was as this project is really just a single feature, not a complete implementation.

Thanks for your interest!

**Comment by FakeRoba** [comment]
Yeah true, thanks for information!
